Default: &defaults
  database: hslides.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: hslides_test.sqlite3
  <<: *defaults

Staging:
  database: hslides_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hslides_production.sqlite3
  poolsize: 100
  <<: *defaults